### ISSUE TITLE
[Meta] Support "main" as a default branch name

### ISSUE THREAD

**Issue by TimidRobot** [creativecommons/creativecommons.org#1125]
## Description
This ticket tracks the variety of changes required to support `main` as a *default branch* name for the [`creativecommons`](https://github.com/creativecommons) and [`cc-archive`](https://github.com/cc-archive) GitHub organizations.

## Rationale
> Master-slave is an oppressive metaphor that will and should never become fully detached from history. Aside from being unprofessional and oppressive it stifles participation

([1.1. Master-slave - Terminology, Power and Oppressive Language](https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.1))

While not everyone may interpret a git `master` branch as representing a "master-slave" metaphor, it is not unreasonable for anyone to do so:

> First appearance of "master" in git is in a CVS helper script[1]:
https://github.com/git/git/commit/3e91311ae750af9bf2e3517b1e701288ac3066b9
> 
> Why is that branch called master? Probably because BitKeeper uses
"master" for its main branch:
> http://www.bitkeeper.org/tips.html#_how_do_i_rebase_my_work_on_top_of_a_different_changeset
> 
> But maybe this "master" isn't the same one that's in "master/slave"?
> See the documentation about
> master/slave repositories:
> https://github.com/bitkeeper-scm/bitkeeper/blob/master/doc/HOWTO.ask#L223
> 
> But repositories and branches aren't the same! They are in BitKeeper:
> https://users.bitkeeper.org/t/branching-with-bk/158/2
> 
> So, yes, the "git master" branch probably isn't even a "master copy"
> reference, but a straight up master/slave reference.

([Re: Replacing "master" reference in git branch names (was Re: Proposal:](https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html))

Continuing to use `master` as a *default branch* name is unwelcoming of too many. We should put our best face forward, not a face that others can easily interpret as hostility or white supremacy.

## Implementation Details
1. Identify and resolve issues that prevent `main` from being used a *default branch* name and track them, below.
2. Project maintainers will decide per repository whether they want to move to using `main` and track them, below.
3. The Creative Commons Engineering team will re-evaluate based on the experience of using `main` in those repositories within ~6 months (2020 end of November or beginning of December)

## Prerequisites
- [x] [Also support "main" as default branch for repo normalization · Issue #48 · creativecommons/ccos-scripts](https://github.com/creativecommons/ccos-scripts/issues/48)
- [x] [Update Pull Request template to support "main" as a default branch name · Issue #10 · creativecommons/.github](https://github.com/creativecommons/.github/issues/10)
- [x] [Support for renaming an existing branch - GitHub Changelog](https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/) (2021-01-19)
  - [github/renaming](https://github.com/github/renaming/): Guidance for changing the default branch name for GitHub repositories

## Additional context
- [Easily rename your Git default branch from master to main - Scott Hanselman](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx)
- [Terminology, Power and Oppressive Language](https://tools.ietf.org/id/draft-knodel-terminology-00.html)
- Additional proof that it has been a "master-slave" metaphor since the beginning:
  - ['Re: kernel.org and GIT tree rebuilding' - MARC](https://marc.info/?l=git&m=111968031816936&w=2) (2005 email from Linus Torvalds to git mailing list)

**Comment by TimidRobot** [comment]
## Related Press
- [GitHub to replace "master" with alternative term to avoid slavery references | ZDNet](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/?ftag=COS-05-10aaa0g&taid=5ee61bd49cfd9b00017a1bb3&utm_campaign=trueAnthem%3A+Trending+Content&utm_medium=trueAnthem&utm_source=twitter)

**Comment by TimidRobot** [comment]
## *Default Branch* Rename Status

### [`cc-archive`](/cc-archive) GitHub Organization

All 184 public repositories are using `main` as the *default branch* name, as of `2021-04-09 15:42 UTC`.

### [`creativecommons`](/creativecommons) GitHub Organization

Of the 84 public repositories, there are still 63 (75%) using a deprecated *default branch* name, as of `2021-04-09 15:42 UTC`:

| Repository | Default Branch |
| ---------- | -------------- |
| [`australian-chapter`](/creativecommons/australian-chapter) | `master` |
| [`business-toolkit-files`](/creativecommons/business-toolkit-files) | `master` |
| [`candela-utility`](/creativecommons/candela-utility) | `master` |
| [`cc-license-chooser`](/creativecommons/cc-license-chooser) | `master` |
| [`cc-usability-prototypes`](/creativecommons/cc-usability-prototypes) | `master` |
| [`cc-wp-theme`](/creativecommons/cc-wp-theme) | `master` |
| [`cc.api`](/creativecommons/cc.api) | `master` |
| [`cc.engine`](/creativecommons/cc.engine) | `master` |
| [`cc.i18n`](/creativecommons/cc.i18n) | `master` |
| [`cc.license`](/creativecommons/cc.license) | `master` |
| [`cc.licenserdf`](/creativecommons/cc.licenserdf) | `master` |
| [`cccatalog`](/creativecommons/cccatalog) | `master` |
| [`cccatalog-api`](/creativecommons/cccatalog-api) | `master` |
| [`cccatalog-data-pipelines`](/creativecommons/cccatalog-data-pipelines) | `master` |
| [`cccatalog-dataviz`](/creativecommons/cccatalog-dataviz) | `master` |
| [`cccatalog-frontend`](/creativecommons/cccatalog-frontend) | `develop` |
| [`CCID-cas`](/creativecommons/CCID-cas) | `master` |
| [`CCID-MediaWiki`](/creativecommons/CCID-MediaWiki) | `master` |
| [`ccos-scripts`](/creativecommons/ccos-scripts) | `master` |
| [`ccrel`](/creativecommons/ccrel) | `master` |
| [`ccrel-guide`](/creativecommons/ccrel-guide) | `master` |
| [`ccsearch-browser-extension`](/creativecommons/ccsearch-browser-extension) | `master` |
| [`ccsearch-infrastructure`](/creativecommons/ccsearch-infrastructure) | `master` |
| [`certificates-landing-page-theme`](/creativecommons/certificates-landing-page-theme) | `master` |
| [`certificates-themes-plugins`](/creativecommons/certificates-themes-plugins) | `master` |
| [`chapters`](/creativecommons/chapters) | `master` |
| [`commoners`](/creativecommons/commoners) | `master` |
| [`creativecommons-base`](/creativecommons/creativecommons-base) | `master` |
| [`creativecommons.github.io`](/creativecommons/creativecommons.github.io) | `master` |
| [`creativecommons.github.io-source`](/creativecommons/creativecommons.github.io-source) | `master` |
| [`creativecommons.org`](/creativecommons/creativecommons.org) | `master` |
| [`global-network-strategy`](/creativecommons/global-network-strategy) | `master` |
| [`image-crawler`](/creativecommons/image-crawler) | `master` |
| [`licensebuttons`](/creativecommons/licensebuttons) | `master` |
| [`magical-pony`](/creativecommons/magical-pony) | `master` |
| [`network-platforms`](/creativecommons/network-platforms) | `master` |
| [`new-creativecommons.org`](/creativecommons/new-creativecommons.org) | `master` |
| [`new-www-plugin`](/creativecommons/new-www-plugin) | `master` |
| [`new-www-theme`](/creativecommons/new-www-theme) | `master` |
| [`open4us.org`](/creativecommons/open4us.org) | `master` |
| [`openpolicynetwork.org`](/creativecommons/openpolicynetwork.org) | `master` |
| [`project-dev2019`](/creativecommons/project-dev2019) | `master` |
| [`queulat`](/creativecommons/queulat) | `master` |
| [`rdfadict`](/creativecommons/rdfadict) | `master` |
| [`reversionary-rights`](/creativecommons/reversionary-rights) | `master` |
| [`rubycas-client-rails`](/creativecommons/rubycas-client-rails) | `master` |
| [`scholars-addenda`](/creativecommons/scholars-addenda) | `master` |
| [`search`](/creativecommons/search) | `master` |
| [`sotc-2016-wordpress`](/creativecommons/sotc-2016-wordpress) | `master` |
| [`sre-report-to-wikijs`](/creativecommons/sre-report-to-wikijs) | `master` |
| [`sre-wiki-js`](/creativecommons/sre-wiki-js) | `master` |
| [`taaccct`](/creativecommons/taaccct) | `gh-pages` |
| [`team-open`](/creativecommons/team-open) | `master` |
| [`termination-of-transfer`](/creativecommons/termination-of-transfer) | `master` |
| [`vocabulary`](/creativecommons/vocabulary) | `master` |
| [`wp-plugin-creativecommons`](/creativecommons/wp-plugin-creativecommons) | `master` |
| [`wp-plugin-vocabulary-blocks`](/creativecommons/wp-plugin-vocabulary-blocks) | `master` |
| [`wp-theme-cc-chapter`](/creativecommons/wp-theme-cc-chapter) | `master` |
| [`wp-theme-cc-sotc`](/creativecommons/wp-theme-cc-sotc) | `master` |
| [`wp-theme-cctoolkit`](/creativecommons/wp-theme-cctoolkit) | `master` |
| [`wp-theme-creativecommons.org`](/creativecommons/wp-theme-creativecommons.org) | `master` |
| [`wp-theme-openglam`](/creativecommons/wp-theme-openglam) | `master` |
| [`wp-theme-summit`](/creativecommons/wp-theme-summit) | `master` |

**Comment by TimidRobot** [comment]
audit script:
```python
#!/usr/bin/env python3
# Standard library
import datetime
import os

# Third-party
from github import Github

ORGS = ["cc-archive", "creativecommons"]
GITHUB_TOKEN = os.environ["ADMIN_GITHUB_TOKEN"]
NOW = datetime.datetime.now(datetime.timezone.utc)

github_client = Github(GITHUB_TOKEN)
print("## *Default Branch* Rename Status\n")
for org in ORGS:
    cc = github_client.get_organization(org)
    repos = list(cc.get_repos())
    deprecated = []
    for repo in repos:
        if repo.default_branch == "master":
            deprecated.append([repo.name, repo.default_branch])
    deprecated.sort(key=lambda l: l[0].casefold())
    percent = float(len(deprecated)) / float(len(repos)) * 100
    print(f"### [`{org}`](/{org}) GitHub Organization\n")
    if int(percent) == 0:
        print(
            f"All {len(repos)} public repositories are using `main` as the"
            f" *default branch* name, as of `{NOW:%Y-%m-%d %H:%M %Z}`.\n"
        )
    else:
        print(
            f"Of the {len(repos)} public repositories, there are still"
            f" {len(deprecated)} ({percent:.0f}%) using a deprecated"
            f" *default branch* name, as of `{NOW:%Y-%m-%d %H:%M %Z}`:\n"
        )
        print("| Repository | Default Branch |")
        print("| ---------- | -------------- |")
        for name, branch in deprecated:
            link = f"[`{name}`](/{org}/{name})"
            print(f"| {link} | `{branch}` |")
        print()
```

**Comment by TimidRobot** [comment]
Only [`creativecommons.github.io`](/creativecommons/creativecommons.github.io) remains and it is covered by [[Bug] Rename default branch to main · Issue #5 · creativecommons/creativecommons.github.io](https://github.com/creativecommons/creativecommons.github.io/issues/5).
