### ISSUE TITLE
includes/total.css is empty and should be removed along with all references to it

### ISSUE THREAD

**Issue by TimidRobot** [creativecommons/creativecommons.org#1151]
## Description

`includes/total.css` is empty and should be removed along with all references to it

## Reproduction
- `creativecommons/creativecommons.org`: [`docroot/includes/total.css`](https://github.com/creativecommons/creativecommons.org/blob/master/docroot/includes/total.css)
- `creativecommons/new-creativecommons.org`: [`docroot/includes/total.css`](https://github.com/creativecommons/new-creativecommons.org/blob/master/docroot/includes/total.css)

## Expectation

Remove include lines:

- [x] `creativecommons/creativecommons.org`: `docroot/includes/deed3.css`: [Lines 2-4](https://github.com/creativecommons/creativecommons.org/blob/master/docroot/includes/deed3.css#L2-L4)
- [x] `creativecommons/creativecommons.org`: `docroot/includes/legalcode.css`: [Lines 2-4](https://github.com/creativecommons/creativecommons.org/blob/master/docroot/includes/legalcode.css#L2-L4)
- [ ] `creativecommons/new-creativecommons.org`: `docroot/includes/deed3.css`: [Lines 2-4](https://github.com/creativecommons/new-creativecommons.org/blob/master/docroot/includes/deed3.css#L2-L4)
- [ ] `creativecommons/new-creativecommons.org`: `docroot/includes/legalcode.css`: [Lines 2-4](https://github.com/creativecommons/new-creativecommons.org/blob/master/docroot/includes/legalcode.css#L2-L4)

Remove files:

- [x] `creativecommons/creativecommons.org`: [`docroot/includes/total.css`](https://github.com/creativecommons/creativecommons.org/blob/master/docroot/includes/total.css)
- [ ] `creativecommons/new-creativecommons.org`: [`docroot/includes/total.css`](https://github.com/creativecommons/new-creativecommons.org/blob/master/docroot/includes/total.css)

## Additional context
The include lines were found with:
```shell
sudo find /var/www -type f \( -name '*.*css' -o -name '*.htm*' -o -name '*.ph*' \) -exec fgrep total.css {} +
```

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by madhhuurrii** [comment]
Hii , can u please guide me in solving this issue as i am a beginner @TimidRobot

**Comment by avats-dev** [comment]
Hi @madhhuurrii , welcome to the CC community. Thanks for showing your interest. :+1: 

---

Now, as @TimidRobot has mentioned above that `includes/total.css` is empty, there is no point of keeping the file then. And it has been referenced also in some files, and those are also needed to be removed. So, a possible workflow could be to:

- basic setup
  - fork the [repo](https://github.com/creativecommons/creativecommons.org) and [this](https://github.com/creativecommons/new-creativecommons.org) one too.
  - clone your forks
  - (optional) add the original repo as upstream remote, but this is not needed
  - create a new branch of your clones for this task

- now, coming back to the issue
  - Be careful while working locally, as there are two different repos involved here.
  - Go to the links in **Remove include lines** under **EXPECTATION** above
  - You'll see some lines highlighted in yellow
  - remove them and leave everything else as it is(**IMPORTANT**)
  - do this for all the 4 references mentioned in the issue
  - after done with this, remove the 2 files mentioned in **Remove files** under **EXPECTATION** above
  - after you've done all this, you can check with 
   `sudo find /var/www -type f \( -name '*.*css' -o -name '*.htm*' -o -name '*.ph*' \) -exec fgrep total.css {} +`
    this should show 0 results, however you can avoid this step if you're not using linux or not familiar with terminal
  - commit your changes to the new branches you've created for this
  - push your changes to your origin(default) remote, and open a PR :tada: 
  - while opening the PR, clearly fill the details so that it links back to the issue.
  - **DONE**, now lookout for the reviews and suggestions on PR. If everything would be good, it would be merged hopefully.

Now, if you're stuck or need any help in any context, you can ping back. Looking forward to your contribution :rocket: .
*(PS: If you're starting out, this might look like a lot, but it's not. Just go gradually with steps and you'll see.)*

> Thanks @TimidRobot , great explanation on the issue.

**Comment by madhhuurrii** [comment]
Thank you so much for the help!!

**Comment by avats-dev** [comment]
> Thank you so much for the help!!

Looking forward to your PR...:rocket:

**Comment by madhhuurrii** [comment]
Thank you for guiding me @avats-dev , i have successfully created my PR , hope it gets merged!!

**Comment by avats-dev** [comment]
Hey @madhhuurrii , nice work. You have to duplicate these works in [new](https://github.com/creativecommons/new-creativecommons.org) repo too, and open a PR there.
> It is similar to what you've done here.

Thanks for your contribution :tada: !

**Comment by TimidRobot** [comment]
@madhhuurrii Thank you! Do you have time to do the same work on [creativecommons/new-creativecommons.org](https://github.com/creativecommons/new-creativecommons.org)?

**Comment by madhhuurrii** [comment]
@TimidRobot Yup! will do the work.

**Comment by TimidRobot** [comment]
Thank you @madhhuurrii
